EXTRA_OBJECTS=
EXTERN_INCLUDE_PATH_VC=
EXTERN_INCLUDE_PATH_GCC=
EXTERN_LIBRARY_PATH=
PLATFORM=win64_gcc64v4_9
TYPE=GEN_EXPERIMENT
IS_DEBUG=no
IS_OPTIM=no
INSTALL_DIR=D:/Archivos de programa/EcosimPro/EcosimPro_6.0.0_DEMO
LIBRARY_DIR=D:/0_Andres/1_Universidad/MUSE/PEL/superpequeproblemas/EcosimPro/EcosimPro/LPRES_v137_without_sources/libs/TRABAJO
PARTITION_FILE=TRABAJO.+r+l10_offdesign.offdesign_partition
EXPERIMENT_FILE=TRABAJO.+r+l10_offdesign.offdesign_partition.s
EXPERIMENT_DIR=D:/0_Andres/1_Universidad/MUSE/PEL/superpequeproblemas/EcosimPro/EcosimPro/LPRES_v137_without_sources/libs/TRABAJO/experiments/+r+l10_offdesign.offdesign_partition/s
EXPERIMENT_DLL=+r+l10_offdesign.offdesign_partition.s.win64_gcc64v4_9
