EXTRA_OBJECTS=
EXTERN_INCLUDE_PATH_VC=
EXTERN_INCLUDE_PATH_GCC=
EXTERN_LIBRARY_PATH=
PLATFORM=win64_gcc64v4_9
TYPE=GEN_EXPERIMENT
IS_DEBUG=no
IS_OPTIM=no
INSTALL_DIR=D:/Archivos de programa/EcosimPro/EcosimPro_6.0.0_DEMO
LIBRARY_DIR=D:/0_Andres/1_Universidad/MUSE/PEL/superpequeproblemas/EcosimPro/LPRES_v137_without_sources/libs/LPRES_EXAMPLES
PARTITION_FILE=LPRES_EXAMPLES.+r+l10_off+design.performance2
EXPERIMENT_FILE=LPRES_EXAMPLES.+r+l10_off+design.performance2.exp1
EXPERIMENT_DIR=D:/0_Andres/1_Universidad/MUSE/PEL/superpequeproblemas/EcosimPro/LPRES_v137_without_sources/libs/LPRES_EXAMPLES/experiments/+r+l10_off+design.performance2/exp1
EXPERIMENT_DLL=+r+l10_off+design.performance2.exp1.win64_gcc64v4_9
